"""create persons table

Revision ID: db042c0f76d1
Revises: 
Create Date: 2025-08-23 21:07:00.513030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db042c0f76d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('civil_state', sa.Enum('S', 'M', 'D', name='marital_status'), nullable=False),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('cpf', name='uq_person_cpf')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###
